apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./../base

namespace: ns-team-ns-team-sites-xp-space-cat-dev

images:
  - name: docker-experience-success-release.dr-uw2.adobeitc.com/franklin/site-status-server
    newTag: 1.2.28
  - name: docker-experience-success-release.dr-uw2.adobeitc.com/franklin/site-status-audit-worker
    newTag: 1.2.28

configMapGenerator:
  - name: franklin-site-status-configs
    envs:
      - configs.env

secretGenerator:
  - name: franklin-site-status-secrets
    namespace: ns-team-ns-team-sites-xp-space-cat-dev
    behavior: create
    env: secrets.env
    type: Opaque

patches:
  - patch: |-
      - op: replace
        path: /spec/virtualhost/fqdn
        value: franklin-site-status-server.ethos09-prod-va7.ethos.adobe.net
    target:
      kind: IngressRoute
      name: franklin-site-status-server-ingress-public
  - patch: |-
      - op: replace
        path: /spec/virtualhost/fqdn
        value: spacecat-rabbitmq.corp.ethos09-prod-va7.ethos.adobe.net
    target:
      kind: IngressRoute
      name: spacecat-rabbitmq-ingress-corp
