openapi: 3.0.0
info:
  title: Franklin Site Status API
  version:
    $ref: "../../package.json#/version"

servers:
  - url: 'http://localhost:8000'

paths:
  /sites:
    get:
      summary: Get all sites
      responses:
        200:
          description: List of all sites
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Site'
  /sites/{domain}:
    get:
      summary: Get specific site by domain
      parameters:
        - name: domain
          in: path
          required: true
          description: The domain of the site
          schema:
            type: string
      responses:
        200:
          description: Site details by domain
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Site'
  /sites.xlsx:
    get:
      summary: Export all sites to Excel
      responses:
        200:
          description: The Excel file with all sites
          content:
            application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
              schema:
                type: string
                format: binary
  /sites.csv:
    get:
      summary: Export all sites to CSV
      responses:
        200:
          description: The CSV file with all sites
          content:
            text/csv:
              schema:
                type: string
                format: binary

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    Site:
      type: object
      description: Information about a specific website and its most recent audit
      properties:
        domain:
          type: string
          description: The domain of the website
        gitHubURL:
          type: string
          description: The GitHub URL where the website's codebase is hosted
        lastAudited:
          type: string
          format: date-time
          description: The date and time when the website was last audited
        audits:
          type: array
          description: The array of audit results
          items:
            $ref: '#/components/schemas/Audit'
        auditError:
          type: string
          description: Any error that occurred during the most recent audit of the site
    Audit:
      type: object
      description: Information about a specific audit of a website
      properties:
        auditedAt:
          type: string
          format: date-time
          description: The date and time when the audit was performed
        isError:
          type: boolean
          description: Whether there was an error during the audit
        errorMessage:
          type: string
          description: The error message, if any
        scores:
          $ref: '#/components/schemas/Scores'
    Scores:
      type: object
      description: Audit scores for different categories
      properties:
        performance:
          type: number
          description: Performance score for the site
        accessibility:
          type: number
          description: Accessibility score for the site
        bestPractices:
          type: number
          description: Best practices score for the site
        seo:
          type: number
          description: SEO score for the site

security:
  - ApiKeyAuth: [ ]  # Use the security scheme named "ApiKeyAuth" for all API paths
