organization: adobe

extends:
  - recommended

apis:
  franklin-site-status@v1:
    root: api.yaml
    rules:
      operation-4xx-response: off
      operation-2xx-response: off
      path-not-include-query: off
