version: '3'
services:
  mongo:
    image: mongo:4.4.24
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.9.5-management
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"

  server:
    image: franklin-site-status-server:${VERSION}
    ports:
      - "8000:8000"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      USER_API_KEY: ${USER_API_KEY}
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      RABBITMQ_USERNAME: "username"
      RABBITMQ_PASSWORD: "password"
      RABBITMQ_SERVICE_SERVICE_HOST: ${RABBITMQ_SERVICE_SERVICE_HOST}
      RABBITMQ_SERVICE_SERVICE_PORT: "5672"
      AUDIT_TASKS_QUEUE_NAME: "audit-tasks-queue"
    depends_on:
      - mongo
      - rabbitmq

  audit-worker:
    image: franklin-site-status-audit-worker:${VERSION}
    environment:
      MONGODB_URI: ${MONGODB_URI}
      AUDIT_TTL_DAYS: ${AUDIT_TTL_DAYS}
      AUDIT_INTERVAL_IN_HOURS: ${AUDIT_INTERVAL_IN_HOURS}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      PAGESPEED_API_KEY: ${PAGESPEED_API_KEY}
      RABBITMQ_USERNAME: "username"
      RABBITMQ_PASSWORD: "password"
      RABBITMQ_SERVICE_SERVICE_HOST: ${RABBITMQ_SERVICE_SERVICE_HOST}
      RABBITMQ_SERVICE_SERVICE_PORT: "5672"
      AUDIT_TASKS_QUEUE_NAME: "audit-tasks-queue"
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongo_data:
