apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklin-site-status-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: franklin-site-status-audit-worker
  template:
    metadata:
      labels:
        app: franklin-site-status-audit-worker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: worker
          image: docker-experience-success-release.dr-uw2.adobeitc.com/franklin/site-status-audit-worker:latest
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: mongodb-uri
            - name: AUDIT_TTL_DAYS
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: audit-ttl-days
            - name: PAGESPEED_API_KEY
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: pagespeed-api-key
