apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklin-site-status-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: franklin-site-status-server
  template:
    metadata:
      labels:
        app: franklin-site-status-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: node-express-server
          image: docker-experience-success-release.dr-uw2.adobeitc.com/franklin-site-status-server:latest
          ports:
            - name: server-port
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: "0.5"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: mongodb-uri
            - name: USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: user-api-key
            - name: ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: admin-api-key


---
apiVersion: v1
kind: Service
metadata:
  name: franklin-site-status-service
  namespace: ns-team-sites-xp-space-cat
  labels:
    app: franklin-site-status-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: franklin-site-status-server
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: franklin-site-status-server-ingress-public
  namespace: ns-team-sites-xp-space-cat
  annotations:
    kubernetes.io/ingress.class: contour-public
spec:
  virtualhost:
    fqdn: franklin-site-status-server.ethos05-prod-va7.ethos.adobe.net
    tls:
      secretName: heptio-contour/cluster-ssl-public
  routes:
    - match: /
      services:
        - name: franklin-site-status-service
          port: 80
