apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklin-site-status-audit-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: franklin-site-status-audit-worker
  template:
    metadata:
      labels:
        app: franklin-site-status-audit-worker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: audit-worker
          image: docker-experience-success-release.dr-uw2.adobeitc.com/franklin/site-status-audit-worker:latest
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: mongodb-uri
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: franklin-site-status-configs
                  key: db-name
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: github-client-id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: github-client-secret
            - name: GITHUB_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: franklin-site-status-configs
                  key: github-api-base-url
            - name: PAGESPEED_API_KEY
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: pagespeed-api-key
            - name: PAGESPEED_API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: franklin-site-status-configs
                  key: pagespeed-api-base-url
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: rabbitmq-password
            - name: AUDIT_TASKS_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: franklin-site-status-configs
                  key: audit-tasks-queue-name
            - name: AUDIT_RESULTS_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: franklin-site-status-configs
                  key: audit-results-queue-name
