apiVersion: apps/v1
kind: Deployment
metadata:
  name: franklin-site-status-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: franklin-site-status-server
  template:
    metadata:
      labels:
        app: franklin-site-status-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: site-status-server
          image: docker-experience-success-release.dr-uw2.adobeitc.com/franklin/site-status-server:latest
          ports:
            - name: server-port
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: mongodb-uri
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: franklin-site-status-configs
                  key: db-name
            - name: USER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: user-api-key
            - name: ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: admin-api-key
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: slack-signing-secret
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: slack-bot-token
            - name: RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: rabbitmq-username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: franklin-site-status-secrets
                  key: rabbitmq-password
            - name: AUDIT_TASKS_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: franklin-site-status-configs
                  key: audit-tasks-queue-name
            - name: AUDIT_RESULTS_QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: franklin-site-status-configs
                  key: audit-results-queue-name

---
apiVersion: v1
kind: Service
metadata:
  name: franklin-site-status-service
  labels:
    app: franklin-site-status-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: franklin-site-status-server
---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: franklin-site-status-server-ingress-public
  annotations:
    kubernetes.io/ingress.class: contour-public
spec:
  virtualhost:
    fqdn: franklin-site-status-server.ethos09-prod-va7.ethos.adobe.net
    tls:
      secretName: heptio-contour/cluster-ssl-public
  routes:
    - match: /
      services:
        - name: franklin-site-status-service
          port: 80
